### ISSUE TITLE
Readme adjustments

### ISSUE THREAD

**Issue by mattleblanc** [luadamek/EoverPAnalysis#10]
Hi!

I've been trying to get the plotting scripts running this morning. I have hit a couple of snags working through the `README.md` under `Plotting/` : 

* The ATLAS style macro seems to have changed since this was running last time -- the following change seems to be fine:
```
(venv_EOPPlotting) lxplus737:Plotting mleblanc$ git diff eop_plotting/plotting_tools.py
diff --git a/Plotting/eop_plotting/plotting_tools.py b/Plotting/eop_plotting/plotting_tools.py
index 23cb7ab..79962e1 100644
--- a/Plotting/eop_plotting/plotting_tools.py
+++ b/Plotting/eop_plotting/plotting_tools.py
@@ -23,8 +23,9 @@ if foundRootNumpy:
     from root_numpy import fill_hist, fill_profile

 if foundAtlasPlots:
-    from atlasplots import atlas_style as astyle
-    astyle.SetAtlasStyle()
+    from atlasplots import atlasstyle as astyle
+    #astyle.SetAtlasStyle()
+    astyle.atlas_style()

 global_scope = []
 CANVAS_COUNTER = 1
```

* The `condor/test/test_scripts/plot_local.sh` script seems to overwrite the environment set up by `setup.sh`, and cannot find `setup_condor.sh` (I'm not sure where this is?). But pointing it to look at `setup.sh` seems to get things running well.

* The very last script (`CreatePlots`) doesn't seem to run on the output from the test script. The output does have histograms in it. I just hit this, and will try to fix it now, but I guess it is looking for `pt_reweighted.root` somewhere and then things deteriorate:

```
(venv_EOPPlotting) lxplus737:Plotting mleblanc$ python create_plots.py
Found atlas plots module. Setting atlas style
Found root_numpy
Initializing histogram manager on file pt_reweighted.root
Error in <TFile::TFile>: file pt_reweighted.root does not exist
Found these channels in the file []
Traceback (most recent call last):
  File "create_plots.py", line 3, in <module>
    from CreatePlots import CreatePlots
  File "/afs/cern.ch/work/m/mleblanc/eoverp/source/EoverPAnalysis/Plotting/CreatePlots.py", line 26, in <module>
    HM = HistogramManager(filename)
  File "/afs/cern.ch/user/m/mleblanc/afs/eoverp/source/EoverPAnalysis/Plotting/eop_plotting/histogram_manager.py", line 16, in __init__
    dir = tFile.Get(self.channels[0]
```

:beers: MLB

**Comment by mattleblanc** [comment]
Ah, OK -- it looks like `CreatePlots.py` just gets edited, and might be a little out-of-date? I will hang tight until @luadamek confirms there's not more to push.

**Comment by luadamek** [comment]
Hi Matt,

    I've been running this successfully on LxPlus.

    Yes, I forgot to push setup_condor.sh to the repo. That is why your submitted jobs are holding when that file fails to transfer.  I just pushed the file. Thanks for pointing this out!

    Yes, CreatePlots.py is a macro that I run to make histograms, but you need to point it at the correct root file to read from. For now, I've just been editing the top of the file.

**Comment by mattleblanc** [comment]
Hi Lukas, thanks for the quick reply, and for pushing `setup_condor.sh` ! I'll give it a shot and see what happens. 👍 

MLB
